// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7dsTHL2IeOksqJiFaYhhJ9jACiUJPQ6w',
    appId: '1:560981141291:web:b63c88357383bcb918c76e',
    messagingSenderId: '560981141291',
    projectId: 'alo-hub-fb0b0',
    authDomain: 'alo-hub-fb0b0.firebaseapp.com',
    storageBucket: 'alo-hub-fb0b0.firebasestorage.app',
    measurementId: 'G-0ZZ4QF8J89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTanq2Lff5aBUxkttoKI-V5yG7sD6rcyY',
    appId: '1:560981141291:android:367d9c148a69869518c76e',
    messagingSenderId: '560981141291',
    projectId: 'alo-hub-fb0b0',
    storageBucket: 'alo-hub-fb0b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCA1SOC0A2hhcdP6HNsHqJt5o4ZSN5dOw',
    appId: '1:560981141291:ios:7b9a4deb61c15f4e18c76e',
    messagingSenderId: '560981141291',
    projectId: 'alo-hub-fb0b0',
    storageBucket: 'alo-hub-fb0b0.firebasestorage.app',
    iosBundleId: 'com.alohub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCA1SOC0A2hhcdP6HNsHqJt5o4ZSN5dOw',
    appId: '1:560981141291:ios:7b9a4deb61c15f4e18c76e',
    messagingSenderId: '560981141291',
    projectId: 'alo-hub-fb0b0',
    storageBucket: 'alo-hub-fb0b0.firebasestorage.app',
    iosBundleId: 'com.alohub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7dsTHL2IeOksqJiFaYhhJ9jACiUJPQ6w',
    appId: '1:560981141291:web:8acacfba0a2cf26818c76e',
    messagingSenderId: '560981141291',
    projectId: 'alo-hub-fb0b0',
    authDomain: 'alo-hub-fb0b0.firebaseapp.com',
    storageBucket: 'alo-hub-fb0b0.firebasestorage.app',
    measurementId: 'G-C78VG5TY61',
  );
}
